<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Aelena.FileApi.Cli</RootNamespace>
    <OutputType>Exe</OutputType>
    <AssemblyName>fileapi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aelena.FileApi.Core\Aelena.FileApi.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

</Project>
